model_params:
  N_c: 2
  N_d:
  - 128
  - 128
  - 64
  - 64
  - 32
  - 32
  - 1
  N_g:
  - 256
  - 128
  - 128
  - 64
  - 64
  - 6
  N_z: 256
  N_x: 6
  SEED: 128764
  conditional: true
  name: gan
settings:
  N_samples: 20000
  N_objects: 2
  STEP: 100
train_params:
  N_batch: 32
  epochs: 50
  lr: 0.001
  beta: 1.001
  print_every: 100
  save_path: models/cvae_nrObjects=10_nrSamples=20000
